// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsYnr672OO_1xoSGN9hmjqbXBByBI8gh0',
    appId: '1:619603998562:web:8093595a05ed26bdf19e3b',
    messagingSenderId: '619603998562',
    projectId: 'onesync-3df51',
    authDomain: 'onesync-3df51.firebaseapp.com',
    storageBucket: 'onesync-3df51.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFAg07_or_rgl4EadUPZ3GkzBFxkH9bp0',
    appId: '1:619603998562:android:bc45931d37f08235f19e3b',
    messagingSenderId: '619603998562',
    projectId: 'onesync-3df51',
    storageBucket: 'onesync-3df51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVhppamG4OP7C4sp8mZxo_8ixWqWdsPcE',
    appId: '1:619603998562:ios:639fb1fdef3d9935f19e3b',
    messagingSenderId: '619603998562',
    projectId: 'onesync-3df51',
    storageBucket: 'onesync-3df51.appspot.com',
    iosBundleId: 'com.thesis3.onesync',
  );
}
